name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake GIF and SVG
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: caio-sts
          output: dist

      - name: Push changes
        uses: actions-x/commit@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          author_name: 'GitHub Action'
          author_email: 'action@github.com'
          message: 'Generated contribution snake graph'
