name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      - name: Push changes
        uses: actions-x/commit@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          author_name: 'GitHub Action'
          author_email: 'action@github.com'
          message: 'Generated contribution snake graph'
